### ISSUE TITLE
Roster CSV/JSON?

### ISSUE THREAD

**Issue by vita10gy** [guga31bb/nflfastR-raw#1]
How possible would also spitting out a CSV or json in 

https://github.com/guga31bb/nflfastR-raw/tree/master/roster

be?

**Comment by mrcaseb** [comment]
There will be a roster csv as well as soon as we think the data is stable.

**Comment by mrcaseb** [comment]
Up to date roster data are now available [here](https://github.com/mrcaseb/nflfastR-roster/tree/master/data). 

Please see also:
https://twitter.com/mrcaseb/status/1305966367246516224?s=21

**Comment by james-childress** [comment]
Looks like the latest push of the roster csv has NA for all rows in the pbp_id and pbp_name columns
