### ISSUE TITLE
Game Raw JSON URLs are improperly formatted

### ISSUE THREAD

**Issue by givemelove** [guga31bb/nflfastR-raw#2]
Hey, I've noticed a variable is still present in the possessionTeam.franchise.currentLogo.url variable.

For instance, the 2020_01_CHI_DET.json file has the following references: `"possessionTeam.franchise.currentLogo.url": "https://static.www.nfl.com/image/private/{formatInstructions}/league/ocvxwnapdvwevupe4tpr"`

**Comment by guga31bb** [comment]
Hmm all we are doing is taking what the NFL posts and saving it so I'm not sure there's anything we can do about this

**Comment by mrcaseb** [comment]
This is not an issue. The nfl provides those urls and we just don't know proper format strings. That's the reason, why we drop this variable during the nflfastR parsing. 

If you want logo urls please use either `nflfastR::teams_colors_logos` in the R package or https://github.com/guga31bb/nflfastR-data/blob/master/teams_colors_logos.csv
