### ISSUE TITLE
Jaguars Team Code Incorrectly Listed for Home Games

### ISSUE THREAD

**Issue by perceptualJonathan** [guga31bb/nflfastR-raw#7]
For every Jaguars home game from the 2001-2015 seasons, the JSON file record that the "data" => "viewer" => "gameDetail" => "plays" => "playStats" => "team.abbreviation" and "team.id" variables are set to their opponent. For whatever reason, the road games do not have this problem, nor do any games from 2016 and onwards. The 1999 and 2000 seasons fine for both road and home games, as well. One maybe notable observation is that for 1999, 2000, and 2016 and beyond, the club code for Jacksonville is "JAX", but for the 2001-2015 seasons, the club code is "JAC".

**Comment by mrcaseb** [comment]
This is correct. It's a bug in the data source of the raw json data. 
We do account for it in the parser in nflfastR. It's a problem in every team abbreviation variable. 
Since we've already fixed this in the parser we don't plan to touch the raw data.
