### ISSUE TITLE
[BUG] I think possessionTeam.abbreviation (etc) is wrong for 2022

### ISSUE THREAD

**Issue by vita10gy** [guga31bb/nflfastR-raw#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### Describe the bug

The possessionTeam information seems (at least occasionally) to be wrong. 

For example play ID 320 in game 7ae7944e-d24c-11ec-b23d-d15a91047884
(the Buf@LA game, only one so far 0 ) 

(9:28) (No Huddle) PENALTY on LA-D.Edwards, False Start, 5 yards, enforced at LA 22 - No Play.

LA has the ball before and after (AKA no special teams confusion in play even)

possessionTeam.id => string (36) "10400610-c40e-a673-1743-2ce2a5d5d731"
possessionTeam.abbreviation => string (3) "BUF"
possessionTeam.nickName => string (5) "Bills"
possessionTeam.franchise.currentLogo.url => string (74) "https://static.www.nfl.com/{formatInstructions}/league/api/clubs/logos/BUF"

Just in case the json and rds are different (though I suspect not) this is from the 2022_01_BUF_LA.json.gz

### Reprex

It's just data, nothing to do

### Expected Behavior

possessionTeam should be the Rams

### nflverse_sitrep

N/A

**Comment by mrcaseb** [comment]
That's correct. There are some games in older seasons as well where the possession team is wrong. We fix that in the parser in nflfastR. 
We can only hope that nfl fixes this in the raw data.
